from __future__ import annotations

import json
from datetime import date, datetime
from pathlib import Path
from uuid import uuid4

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "uploads" / "source"
COVERS = ROOT / "uploads" / "covers"
DATA = ROOT / "data" / "library.json"

BOOKS_DATA = [
    {
        "title": "FAANG SDET DS Missing Problems",
        "author": "Debdip (Personal Notes)",
        "pages": 21,
        "priority": 5,
        "source": "WhatsApp Image 2026-09-18 at 9.26.54 AM (1).jpeg",
        "rotate": 0,
        "notes": "Bound study guide covering 17 interview DSA problems: linked lists, trees, stacks, graphs, heaps, backtracking, and dynamic programming.",
    },
    {
        "title": "Python SDET Detailed Revision Book",
        "author": "Debdip (Personal Notes)",
        "pages": 80,
        "priority": 5,
        "source": "WhatsApp Image 2026-09-18 at 9.26.55 AM (1).jpeg",
        "rotate": 0,
        "notes": "Comprehensive revision guide for Senior SDETs: Python fundamentals, core data types, time complexity, and automation architecture.",
    },
    {
        "title": "Playwright with pytest & Python: The Complete Book",
        "author": "Debdip (Personal Notes)",
        "pages": 72,
        "priority": 5,
        "source": "WhatsApp Image 2026-09-18 at 9.26.55 AM.jpeg",
        "rotate": 0,
        "notes": "Hands-on, code-first automation guide: Playwright synchronous API, pytest, POM framework, JSON data-driven testing, MongoDB, and CI/CD.",
    },
    {
        "title": "LeetCode Solutions Book",
        "author": "Debdip (Personal Notes)",
        "pages": 61,
        "priority": 5,
        "source": "WhatsApp Image 2026-09-18 at 9.28.25 AM (1).jpeg",
        "rotate": 0,
        "notes": "52 Problems Solved in Python with Visual Explanations (24 Easy, 23 Medium, 5 Hard).",
    },
    {
        "title": "Web & API Architecture Reference Guide",
        "author": "Debdip (Personal Notes)",
        "pages": 50,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.26.56 AM.jpeg",
        "rotate": 0,
        "notes": "Reference guide on Web & APIs: Repositories, Routes, Controllers, Middleware, Validation, and service integrations.",
    },
    {
        "title": "Comprehensive DeepEval: Testing a Chatbot with Python",
        "author": "Perplexity / DeepEval",
        "pages": 40,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.15 AM.jpeg",
        "rotate": 0,
        "notes": "Tutorial packet on testing chatbot LLM outputs, fundamental checks, custom test metrics, and automated evaluation pipelines.",
    },
    {
        "title": "Programming in Python: A Problem Solving Approach (2nd Edition)",
        "author": "Reema Thareja",
        "pages": 560,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.26.56 AM (2).jpeg",
        "rotate": 0,
        "notes": "Oxford Higher Education textbook (ISBN 978-0-19-012408-5) covering problem solving, Python data structures, OOP, and algorithms.",
    },
    {
        "title": "Let Us Python (7th Edition)",
        "author": "Yashavant Kanetkar",
        "pages": 520,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.01 AM (1).jpeg",
        "rotate": 0,
        "notes": "BPB Publications edition covering Python basics, OOP, GUI development, network programming, and security.",
    },
    {
        "title": "Data Analytics with R",
        "author": "Dr. Bharti Motwani",
        "pages": 480,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.26.58 AM (1).jpeg",
        "rotate": 180,
        "notes": "Wiley India Engineering Management reference textbook covering data cleansing, modeling, statistical tests, and R programming.",
    },
    {
        "title": "Deep Learning with Python (2nd Edition)",
        "author": "François Chollet",
        "pages": 504,
        "priority": 5,
        "source": "WhatsApp Image 2026-09-18 at 9.28.07 AM (1).jpeg",
        "rotate": 0,
        "notes": "Manning edition by the creator of Keras. Covers deep learning fundamentals, computer vision, NLP, and generative models.",
    },
    {
        "title": "Head First Agile",
        "author": "Andrew Stellman and Jennifer Greene",
        "pages": 468,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.23 AM (2).jpeg",
        "rotate": 0,
        "notes": "O'Reilly guide to understanding Agile principles, Scrum, Kanban, and passing the PMI-ACP certification.",
    },
    {
        "title": "Head First Data Analysis / Excel",
        "author": "Michael Milton",
        "pages": 480,
        "priority": 3,
        "source": "WhatsApp Image 2026-09-18 at 9.28.18 AM.jpeg",
        "rotate": 0,
        "notes": "O'Reilly brain-friendly guide to data exploration, pivot tables, spreadsheet analysis, and statistical decision making.",
    },
    {
        "title": "Meditations",
        "author": "Marcus Aurelius",
        "pages": 256,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.26.57 AM (1).jpeg",
        "rotate": 0,
        "notes": "Classic Stoic reflections on self-discipline, duty, resilience, and virtue by the Roman Emperor.",
    },
    {
        "title": "Introduction to Bhagavad-gita",
        "author": "A. C. Bhaktivedanta Swami Prabhupada",
        "pages": 120,
        "priority": 3,
        "source": "WhatsApp Image 2026-09-18 at 9.26.58 AM (2).jpeg",
        "rotate": 0,
        "notes": "Bhaktivedanta Book Trust introductory exposition of the fundamental teachings and philosophy of the Bhagavad Gita.",
    },
    {
        "title": "Bhagavad-gita As It Is",
        "author": "A. C. Bhaktivedanta Swami Prabhupada",
        "pages": 924,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.11 AM (1).jpeg",
        "rotate": 0,
        "notes": "Complete hardcover edition with original Sanskrit text, transliteration, English synonyms, translation, and elaborate purports.",
    },
    {
        "title": "The Science of Self-Realization",
        "author": "A. C. Bhaktivedanta Swami Prabhupada",
        "pages": 360,
        "priority": 3,
        "source": "WhatsApp Image 2026-09-18 at 9.28.09 AM (1).jpeg",
        "rotate": 0,
        "notes": "BBT collection of essays, talks, and dialogues exploring karma, reincarnation, superconsciousness, and bhakti yoga.",
    },
    {
        "title": "Shrimad Bhagavad Gita (Code 2099)",
        "author": "Gita Press, Gorakhpur",
        "pages": 280,
        "priority": 3,
        "source": "WhatsApp Image 2026-09-18 at 9.28.14 AM.jpeg",
        "rotate": 0,
        "notes": "Gita Press authoritative edition (Code 2099) with original Sanskrit shlokas and precise Hindi commentary.",
    },
    {
        "title": "Gita for Everyday Living",
        "author": "Swami Sunirmalananda",
        "pages": 240,
        "priority": 3,
        "source": "WhatsApp Image 2026-09-18 at 9.28.16 AM.jpeg",
        "rotate": 0,
        "notes": "Chinmaya Mission / Vedanta edition exploring practical applications of Gita wisdom for daily life challenges.",
    },
    {
        "title": "The Power of Thoughts",
        "author": "Swami Mukundananda",
        "pages": 256,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.15 AM (2).jpeg",
        "rotate": 0,
        "notes": "Penguin Ananda edition exploring conscious thought cultivation, mind management, and spiritual growth.",
    },
    {
        "title": "Life's Amazing Secrets: How to Find Balance and Purpose",
        "author": "Gaur Gopal Das",
        "pages": 232,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.12 AM (2).jpeg",
        "rotate": 0,
        "notes": "Practical four-wheel framework on friendships, inner peace, service, and purpose by the popular ISKCON monk.",
    },
    {
        "title": "Extra Sensory Potentials of the Mind",
        "author": "Pandit Shriram Sharma Acharya",
        "pages": 160,
        "priority": 3,
        "source": "WhatsApp Image 2026-09-18 at 9.27.12 AM.jpeg",
        "rotate": 0,
        "notes": "All World Gayatri Pariwar treatise on latent cognitive abilities, intuition, meditation, and yogic consciousness.",
    },
    {
        "title": "Dignity of Organisational Skill",
        "author": "Pandit Shriram Sharma Acharya",
        "pages": 120,
        "priority": 3,
        "source": "WhatsApp Image 2026-09-18 at 9.28.13 AM (1).jpeg",
        "rotate": 0,
        "notes": "Akhand Jyoti Sansthan booklet on systematic organization, group coordination, and purposeful work ethics.",
    },
    {
        "title": "How to Overcome Mental Tension",
        "author": "Swami Gokulananda",
        "pages": 112,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.28.12 AM.jpeg",
        "rotate": 0,
        "notes": "Ramakrishna Mission Institute of Culture guide on emotional equilibrium, mind training, and mental tranquility.",
    },
    {
        "title": "Code Name God: The Spiritual Odyssey of a Man of Science",
        "author": "Mani Bhaumik",
        "pages": 240,
        "priority": 3,
        "source": "WhatsApp Image 2026-09-18 at 9.27.22 AM.jpeg",
        "rotate": 0,
        "notes": "Autobiography of physicist Mani Bhaumik tracing his journey from famine in Bengal to LASIK co-invention and cosmology.",
    },
    {
        "title": "Feeling Good: The New Mood Therapy",
        "author": "David D. Burns",
        "pages": 736,
        "priority": 3,
        "source": "WhatsApp Image 2026-09-18 at 9.27.00 AM (1).jpeg",
        "rotate": 0,
        "notes": "Clinically proven drug-free Cognitive Behavioral Therapy (CBT) techniques to overcome depression, anxiety, and guilt.",
    },
    {
        "title": "The Courage to Be Disliked",
        "author": "Ichiro Kishimi and Fumitake Koga",
        "pages": 288,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.03 AM (2).jpeg",
        "rotate": 0,
        "notes": "Adlerian psychology presented through an enlightening dialogue on courage, self-determination, and personal freedom.",
    },
    {
        "title": "Ikigai: The Japanese Secret to a Long and Happy Life",
        "author": "Héctor García and Francesc Miralles",
        "pages": 208,
        "priority": 3,
        "source": "WhatsApp Image 2026-09-18 at 9.27.04 AM (2).jpeg",
        "rotate": 0,
        "notes": "Finding purpose, flow, and joy through the wisdom and habits of Japan's centenarians in Okinawa.",
    },
    {
        "title": "The Mountain Is You: Transforming Self-Sabotage into Self-Mastery",
        "author": "Brianna Wiest",
        "pages": 248,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.04 AM.jpeg",
        "rotate": 0,
        "notes": "Thought Catalog bestselling guide to overcoming subconscious emotional blockages and transforming self-sabotage into growth.",
    },
    {
        "title": "Eat That Frog!: 21 Great Ways to Stop Procrastinating",
        "author": "Brian Tracy",
        "pages": 144,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.06 AM (1).jpeg",
        "rotate": 0,
        "notes": "Time management and productivity classic focusing on tackling the most critical, challenging tasks first.",
    },
    {
        "title": "No Excuses!: The Power of Self-Discipline",
        "author": "Brian Tracy",
        "pages": 304,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.26.59 AM (2).jpeg",
        "rotate": 180,
        "notes": "Vanguard Press edition detailing 21 principles of self-discipline across personal goals, finances, career, and overall health.",
    },
    {
        "title": "Atomic Habits: Tiny Changes, Remarkable Results",
        "author": "James Clear",
        "pages": 320,
        "priority": 5,
        "source": "WhatsApp Image 2026-09-18 at 9.27.16 AM (1).jpeg",
        "rotate": 0,
        "notes": "Bestselling habit formation guide based on 1% marginal gains, system design, and the four laws of behavior change.",
    },
    {
        "title": "Deep Work: Rules for Focused Success in a Distracted World",
        "author": "Cal Newport",
        "pages": 304,
        "priority": 5,
        "source": "WhatsApp Image 2026-09-18 at 9.27.17 AM (1).jpeg",
        "rotate": 0,
        "notes": "Practical strategies to cultivate intense cognitive focus and master complicated tasks in an era of constant distraction.",
    },
    {
        "title": "Zero to One: Notes on Startups, or How to Build the Future",
        "author": "Peter Thiel with Blake Masters",
        "pages": 224,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.19 AM (1).jpeg",
        "rotate": 0,
        "notes": "Contrarian philosophy on technology startups, creating singular value monopolies, and escaping competition.",
    },
    {
        "title": "The Power of Positive Thinking",
        "author": "Norman Vincent Peale",
        "pages": 320,
        "priority": 3,
        "source": "WhatsApp Image 2026-09-18 at 9.27.20 AM (1).jpeg",
        "rotate": 0,
        "notes": "Classic guide to cultivating mental resilience, optimism, inner peace, and confidence.",
    },
    {
        "title": "Think and Grow Rich (21st Century Edition)",
        "author": "Napoleon Hill",
        "pages": 384,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.14 AM.jpeg",
        "rotate": 0,
        "notes": "Definitive 21st-century edition of Napoleon Hill's legendary philosophy of personal success and wealth creation.",
    },
    {
        "title": "The Richest Man in Babylon",
        "author": "George S. Clason",
        "pages": 160,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.16 AM.jpeg",
        "rotate": 0,
        "notes": "Fingerprint! Publishing edition (ISBN 978-81-943657-3-0). Timeless Babylonian parables on thrift, budgeting, and investment.",
    },
    {
        "title": "Range: How Generalists Triumph in a Specialized World",
        "author": "David Epstein",
        "pages": 352,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.28.17 AM.jpeg",
        "rotate": 0,
        "notes": "Compelling case for why broad thinking, generalists, late bloomers, and diverse knowledge thrive in unpredictable fields.",
    },
    {
        "title": "The Five Dysfunctions of a Team",
        "author": "Patrick Lencioni",
        "pages": 240,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.06 AM.jpeg",
        "rotate": 0,
        "notes": "Influential leadership fable outlining the root causes of team politics, friction, and dysfunction.",
    },
    {
        "title": "The Case of the Bonsai Manager",
        "author": "R. Gopalakrishnan",
        "pages": 256,
        "priority": 3,
        "source": "WhatsApp Image 2026-09-18 at 9.27.07 AM (1).jpeg",
        "rotate": 0,
        "notes": "Former Tata Sons executive explores intuition, biological metaphors, and adaptive thinking in management.",
    },
    {
        "title": "The Ambuja Story",
        "author": "Narotam Sekhsaria",
        "pages": 384,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.08 AM (1).jpeg",
        "rotate": 0,
        "notes": "Inspiring corporate autobiography of Narotam Sekhsaria building Ambuja Cements through trust and innovation.",
    },
    {
        "title": "Elon Musk: Quest for a Fantastic Future",
        "author": "Ashlee Vance",
        "pages": 288,
        "priority": 3,
        "source": "WhatsApp Image 2026-09-18 at 9.27.06 AM (2).jpeg",
        "rotate": 0,
        "notes": "Young readers adapted biography chronicling Elon Musk's audacious journey with Tesla, SpaceX, and SolarCity.",
    },
    {
        "title": "Sachin Tendulkar (Pictorial Biography)",
        "author": "Pictorial Biography series",
        "pages": 120,
        "priority": 3,
        "source": "WhatsApp Image 2026-09-18 at 9.27.23 AM.jpeg",
        "rotate": 0,
        "notes": "Illustrated retrospective celebrating the record-breaking cricket career and philosophy of Sachin Tendulkar.",
    },
    {
        "title": "Bhagat Singh (Pictorial Biography)",
        "author": "Jain Publishers",
        "pages": 128,
        "priority": 3,
        "source": "WhatsApp Image 2026-09-18 at 9.27.24 AM (1).jpeg",
        "rotate": 0,
        "notes": "Pictorial biography chronicling the sacrifice, intellect, and revolutionary writings of Shaheed Bhagat Singh.",
    },
    {
        "title": "Man's Search for Meaning",
        "author": "Viktor E. Frankl",
        "pages": 160,
        "priority": 5,
        "source": "WhatsApp Image 2026-09-18 at 9.27.11 AM (2).jpeg",
        "rotate": 0,
        "notes": "Classic tribute to resilience from the Holocaust, formulating Frankl's logotherapy and purpose-driven psychology.",
    },
    {
        "title": "Zen: The Art of Simple Living",
        "author": "Shunmyo Masuno",
        "pages": 224,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.13 AM (1).jpeg",
        "rotate": 0,
        "notes": "100 daily mindful Zen habits by the head priest of a 450-year-old Zen Buddhist temple in Japan.",
    },
    {
        "title": "HBR Guide to Better Business Writing",
        "author": "Bryan A. Garner",
        "pages": 240,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.18 AM (1).jpeg",
        "rotate": 0,
        "notes": "Harvard Business Review guide on clear, engaging, and persuasive communication in emails, reports, and memos.",
    },
    {
        "title": "The Quick and Easy Way to Effective Speaking",
        "author": "Dale Carnegie",
        "pages": 224,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.18 AM (2).jpeg",
        "rotate": 0,
        "notes": "Dale Carnegie's time-tested techniques for conquering public speaking fear and delivering dynamic presentations.",
    },
    {
        "title": "Emotional Intelligence Habits",
        "author": "Travis Bradberry",
        "pages": 256,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.25 AM.jpeg",
        "rotate": 0,
        "notes": "Actionable micro-habits designed to boost emotional intelligence (EQ), self-management, and social empathy.",
    },
    {
        "title": "The Last Lecture",
        "author": "Randy Pausch with Jeffrey Zaslow",
        "pages": 224,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.26 AM (2).jpeg",
        "rotate": 0,
        "notes": "Unforgettable life wisdom and optimism from Carnegie Mellon computer science professor Randy Pausch.",
    },
    {
        "title": "Let's Talk Money",
        "author": "Monika Halan",
        "pages": 256,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.26 AM.jpeg",
        "rotate": 0,
        "notes": "Practical, jargon-free personal finance framework tailored for Indian professionals and families.",
    },
    {
        "title": "Mossad: The Greatest Missions of the Israeli Secret Service",
        "author": "Michael Bar-Zohar and Nissim Mishal",
        "pages": 400,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.27 AM (1).jpeg",
        "rotate": 0,
        "notes": "Dramatic history of Israel's foreign intelligence agency and its most secretive global operations.",
    },
    {
        "title": "Deep Focus: Reflections on Cinema",
        "author": "Satyajit Ray",
        "pages": 200,
        "priority": 3,
        "source": "WhatsApp Image 2026-09-18 at 9.27.22 AM (2).jpeg",
        "rotate": 0,
        "notes": "HarperCollins collection of legendary filmmaker Satyajit Ray's essays on direction, screenwriting, and film theory.",
    },
    {
        "title": "The Hungry Tide",
        "author": "Amitav Ghosh",
        "pages": 416,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.09 AM.jpeg",
        "rotate": 0,
        "notes": "HarperCollins novel exploring human relationships, myth, and danger amidst the tides and mangroves of the Sundarbans.",
    },
    {
        "title": "The Home and the World (Ghare Baire)",
        "author": "Rabindranath Tagore",
        "pages": 224,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.27.03 AM (1).jpeg",
        "rotate": 0,
        "notes": "Rabindranath Tagore's literary classic depicting the clash of swadeshi nationalism, personal morality, and love.",
    },
    {
        "title": "Vagabond (Manga Series)",
        "author": "Takehiko Inoue",
        "pages": 240,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.28.09 AM.jpeg",
        "rotate": 0,
        "notes": "Viz Media acclaimed historical manga based on Eiji Yoshikawa's novel Musashi, following the legendary swordsman.",
    },
    {
        "title": "40 Sufi Comics",
        "author": "Mohammed Ali Vakil and Mohammed Arif Vakil",
        "pages": 120,
        "priority": 3,
        "source": "WhatsApp Image 2026-09-18 at 9.26.56 AM (1).jpeg",
        "rotate": 0,
        "notes": "Illustrated spiritual graphic book conveying timeless moral tales, Sufi parables, and Quranic verses.",
    },
    {
        "title": "Back to the Roots: Celebrating Indian Wisdom and Wellness",
        "author": "Luke Coutinho with Tamannaah",
        "pages": 288,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.28.10 AM.jpeg",
        "rotate": 0,
        "notes": "Penguin guide celebrating ancient Indian wellness practices, balanced nutrition, sleep, and natural healing.",
    },
    {
        "title": "The Bitcoin Saga: A Mixed Montage",
        "author": "Rachna Singh",
        "pages": 256,
        "priority": 3,
        "source": "WhatsApp Image 2026-09-18 at 9.28.16 AM (1).jpeg",
        "rotate": 0,
        "notes": "Bloomsbury edition chronicling the emergence of Bitcoin, blockchain disruption, cryptocurrency mining, and financial futures.",
    },
    {
        "title": "One Indian Girl",
        "author": "Chetan Bhagat",
        "pages": 280,
        "priority": 3,
        "source": "WhatsApp Image 2026-09-18 at 9.28.18 AM (1).jpeg",
        "rotate": 0,
        "notes": "Rupa Publications novel exploring career aspirations, modern relationships, and societal expectations through protagonist Radhika Mehta.",
    },
    {
        "title": "Own Your Body: A Doctor's Life-Saving Tips",
        "author": "Dr. Shiv Sarin",
        "pages": 352,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.28.20 AM.jpeg",
        "rotate": 0,
        "notes": "Foreword by Prof. C.N.R. Rao. Renowned liver specialist Dr. Shiv Sarin shares essential preventative medical guidance.",
    },
    {
        "title": "How Not to Die",
        "author": "Dr. Michael Greger with Gene Stone",
        "pages": 576,
        "priority": 4,
        "source": "WhatsApp Image 2026-09-18 at 9.28.21 AM (1).jpeg",
        "rotate": 0,
        "notes": "Scientific, evidence-backed nutritional advice proven to prevent and reverse leading chronic diseases.",
    },
    {
        "title": "Sapiens: A Brief History of Humankind",
        "author": "Yuval Noah Harari",
        "pages": 464,
        "priority": 5,
        "source": "WhatsApp Image 2026-09-18 at 9.28.22 AM.jpeg",
        "rotate": 0,
        "notes": "Vintage edition exploring human evolution, societal myths, money, empire, and our species' trajectory.",
    },
    {
        "title": "Nexus: A Brief History of Information Networks from the Stone Age to AI",
        "author": "Yuval Noah Harari",
        "pages": 528,
        "priority": 5,
        "source": "WhatsApp Image 2026-09-18 at 9.28.24 AM.jpeg",
        "rotate": 0,
        "notes": "Penguin / Fern Press edition analyzing how information networks and artificial intelligence reshape truth, power, and civilizations.",
    },
    {
        "title": "OPEN Magazine (July 2026 Issue)",
        "author": "Open Media Network",
        "pages": 64,
        "priority": 2,
        "source": "WhatsApp Image 2026-09-18 at 9.26.54 AM.jpeg",
        "rotate": 0,
        "notes": "Current affairs periodical featuring Prime Minister Narendra Modi's Mann Ki Baat address and features on classical Sanskrit revival.",
    },
]

def main() -> None:
    COVERS.mkdir(parents=True, exist_ok=True)
    DATA.parent.mkdir(parents=True, exist_ok=True)

    books = []
    print(f"Processing {len(BOOKS_DATA)} books...")

    for item in BOOKS_DATA:
        src = SOURCE / item["source"]
        if not src.exists():
            print(f"ERROR: missing source file {item['source']}")
            continue

        slug = "".join(ch if ch.isalnum() else "-" for ch in item["title"].lower()).strip("-")[:60]
        dest = COVERS / f"{slug}.jpg"

        image = ImageOps.exif_transpose(Image.open(src))
        if item.get("rotate", 0) != 0:
            image = image.rotate(item["rotate"], expand=True)

        image.thumbnail((600, 900), Image.Resampling.LANCZOS)
        image.convert("RGB").save(dest, "JPEG", quality=92)

        books.append(
            {
                "id": str(uuid4()),
                "title": item["title"],
                "author": item["author"],
                "pages": item["pages"],
                "pages_read": 0,
                "cover_path": str(dest),
                "notes": item["notes"],
                "priority": item["priority"],
                "status": "unread",
                "source_image": item["source"],
                "added_at": datetime.now().isoformat(timespec="seconds"),
            }
        )

    settings = {
        "pages_per_hour": 30,
        "minutes_per_day": 45,
        "mode": "sequential",
        "start_date": date.today().isoformat(),
        "rest_weekdays": [],
    }
    if DATA.exists():
        try:
            old_lib = json.loads(DATA.read_text(encoding="utf-8"))
            if "settings" in old_lib:
                settings = old_lib["settings"]
        except Exception:
            pass

    payload = {
        "books": books,
        "settings": settings,
        "progress_log": [],
    }

    DATA.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"Successfully updated seed data with {len(books)} books!")


if __name__ == "__main__":
    main()
